# Información del sitio
title: Since Marketing
email: info@since.com
description: >- 
  Since Marketing - Agencia de Marketing Digital especializada en estrategias 
  de crecimiento para empresas en Latinoamérica.
baseurl: ""
url: "https://since.com"

# Redes sociales
social:
  instagram: https://instagram.com/since
  facebook: https://facebook.com/since
  linkedin: https://linkedin.com/company/since

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-paginate

# Paginación (removida la duplicación)
paginate: 10
paginate_path: "/blog/page/:num/"

# URLs
permalink: :slug

# Compresión HTML
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: []

# Collections
collections:
  redirects:
    output: true
  specialized:
    output: true
    permalink: /servicios/:path
  commercial:
    output: true
    permalink: /nosotros/:path
  residential:
    output: true
    permalink: /informacion/:path

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      schema: "BlogPosting"
  - scope:
      path: ""
      type: "servicios"
    values:
      layout: "servicio"
      schema: "Service"
  - scope:
      path: ""
      type: "nosotros"
    values:
      layout: "nosotros"
  - scope:
      path: ""
      type: "informacion"
    values:
      layout: "informacion"